### ISSUE TITLE
[Bug] get_details() can't handle more than 100 alerts at a time

### ISSUE THREAD

**Issue by csanders-git** [code42/py42#257]
### Description
alert_service.get_details() takes a list of alert_ids. It seems that the API call in the background can only take 100 alert IDs at one time. This can easily be avoided on the client side, but it'd be nice if the API wrapper handled this.

### Steps to Reproduce

1.  Perform an AlertQuery (`sdk.alerts.search(query)`) that generates more than 100 results
2. Iterate over the returned alerts and store the `id` element in a list.
3. Ensure the list is over length 100 (101 will do)
4. Pass the list to `sdk.alerts.get_details`

### Expected Behavior

    alerts = sdk.alerts.get_details(alert_ids[0:101])['alerts']
    print(len(alerts))

    > 101

### Actual Behavior

```
python3 start.py
Traceback (most recent call last):
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/services/_connection.py", line 272, in _handle_error
    response.raise_for_status()
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://alert-service-default.prod.ffs.us2.code42.com/svc/api/v1/query-details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 26, in <module>
    main()
  File "start.py", line 20, in main
    c42_engine.code_42_alerts(conn)
  File "/Users/<redacted>/pulls/<redacted>/automation/c42_engine.py", line 68, in code_42_alerts
    get_exfil_details(sdk, interested_alerts)
  File "/Users/<redacted>/pulls/<redacted>/automation/c42_engine.py", line 35, in get_exfil_details
    alerts = sdk.alerts.get_details(alert_ids[0:101])['alerts']
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/clients/alerts.py", line 43, in get_details
    return self._alert_service.get_details(alert_ids)
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/services/alerts.py", line 31, in get_details
    results = self._connection.post(uri, json=data)
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/services/_connection.py", line 145, in post
    return self.request(u"POST", url, data=data, **kwargs)
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/services/_connection.py", line 209, in request
    _handle_error(method, url, response)
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/services/_connection.py", line 274, in _handle_error
    raise_py42_error(ex)
  File "/Users/<redacted>/pulls/<redacted>/automation/venv/lib/python3.8/site-packages/py42/exceptions.py", line 245, in raise_py42_error
    raise Py42BadRequestError(raised_error)
py42.exceptions.Py42BadRequestError: Failure in HTTP call 400 Client Error: Bad Request for url: https://alert-service-default.prod.ffs.us2.code42.com/svc/api/v1/query-details
```
### Suggestion
Modify https://github.com/code42/py42/blob/e85c116648780e924af5ef3a90c16ca8f4c53836/src/py42/clients/alerts.py#L43
to add something like

```
    alert_detail_results = []
    max_details_size = 100
    for alert_index_start in range(0, len(alert_ids), max_details_size):
        if (alert_index_start + max_details_size) >= len(alert_ids):
            alert_index_end = len(alert_ids)
        else:
            alert_index_end = alert_index_start + max_details_size
        alert_detail_results += self._alert_service.get_details(alert_ids[alert_index_start:alert_index_end])
   return alert_detail_results
```

### Basic Information

- py42 version:  1.10.1
- python version:  3.8.6
- operating system: MacOS 10.15

**Comment by DiscoRiver** [comment]
Underlying API refence: https://developer.code42.com/api/#operation/Alerts_QueryAlertDetails
Py42 Doc: https://py42docs.code42.com/en/stable/methoddocs/alerts.html#alerts

I think we should add a new error if the elements in alert_ids exceeds 100 when calling `sdk.alerts.get_details`, and update the Py42 documentation to indicate that a maximum of 100 elements should be included in each call. 

To update the logic within Py42, we would need to consider what happens if one request in the chain fails, from a single call to `sdk.alerts.get_details`. This would add a complexity that I think is unnecessary for Py42, and we should instead have users handle each call & response per 100 elements in `alert_ids`.
