### ISSUE TITLE
[Bug] 400 bad request when attempting to refresh user attributes for a user who doesn't yet have detection list profile

### ISSUE THREAD

**Issue by ceciliastevens** [code42/py42#297]
### Description

When attempting to call `sdk.detectionlists.refresh_user_scim_attributes`, a 400 bad request error is returned if the user hasn't yet had a detection profile created.

### Steps to Reproduce

```
>>> from py42 import sdk
>>> c42 = sdk.from_local_account(hostname, username, password)
>>> testuser = c42.users.get_by_username(user_email)
>>> testuid = testuser.data['users'][0]['userUid']
>>> c42.detectionlists.refresh_user_scim_attributes(testuid)
```

### Expected Behavior

The call returns a `Py42Response` containing information about the user who was refreshed, or returns an error explaining why the user could not be refreshed.

### Actual Behavior

```
>>> c42.detectionlists.refresh_user_scim_attributes(testuid)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/py42/services/_connection.py", line 279, in _handle_error
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://ecm-east.us.code42.com/svc/api/v2/user/refresh

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/py42/clients/detectionlists.py", line 147, in refresh_user_scim_attributes
    return self._user_profile_service.refresh(user_id)
  File "/usr/local/lib/python3.9/site-packages/py42/services/detectionlists/user_profile.py", line 212, in refresh
    return self._connection.post(uri, json=data)
  File "/usr/local/lib/python3.9/site-packages/py42/services/_connection.py", line 143, in post
    return self.request(u"POST", url, data=data, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/py42/services/_connection.py", line 206, in request
    _handle_error(method, url, response)
  File "/usr/local/lib/python3.9/site-packages/py42/services/_connection.py", line 281, in _handle_error
    raise_py42_error(ex)
  File "/usr/local/lib/python3.9/site-packages/py42/exceptions.py", line 295, in raise_py42_error
    raise Py42BadRequestError(raised_error)
py42.exceptions.Py42BadRequestError: Failure in HTTP call 400 Client Error: Bad Request for url: https://ecm-east.us.code42.com/svc/api/v2/user/refresh
```

### Basic Information

- py42 version: 1.11.1
- python version: 3.9.1
- operating system: Mac OS 10.15.7

**Comment by alanag13** [comment]
This seems related to #185, which we've known about for a while... I'll get something added to our internal tracking to make sure we get this looked at.

**Comment by timabrmsn** [comment]
It seems no all existing users and newly created users automatically get a detectionlist profile created on the backend, so this error should no longer be happening.
